import Link from 'next/link';
import { notFound } from 'next/navigation';
import { isLang } from '@/lib/i18n';
import { buildPageMetadata } from '@/lib/seo';
import HomeStagingSection from '@/components/HomeStagingSection';

export async function generateMetadata({ params }) {
  const { lang } = await params;
  if (!isLang(lang)) notFound();
  return buildPageMetadata({
    title: lang === 'fr' ? 'Vendre ou acheter à Valbonne et sur la Côte d’Azur | Côte d’Azur Agency' : 'Sell or buy a property on the French Riviera | Côte d’Azur Agency',
    description: lang === 'fr' ? 'Estimation, home staging, stratégie de vente et recherche immobilière avec Stephan. Un accompagnement en français et en anglais sur la Côte d’Azur.' : 'Property valuation, home staging, sales strategy and buying support with Stephan. Local guidance in French and English on the French Riviera.',
    lang, pathname: `/${lang}/services`,
  });
}

export default async function ServicesPage({ params }) {
  const { lang } = await params;
  if (!isLang(lang)) notFound();
  const fr = lang === 'fr';
  const sellerSteps = fr ? [
    ['Comprendre votre bien', 'Nous échangeons sur ses caractéristiques, son état, les documents disponibles, vos objectifs et votre calendrier. Les particularités de la propriété doivent être examinées avant de parler de positionnement.'],
    ['Définir une stratégie de vente', 'L’estimation et les éléments de comparaison servent à discuter du prix, de la présentation et des actions de commercialisation adaptées. Les modalités de la mission sont convenues avec vous.'],
    ['Présenter et qualifier', 'Nous organisons la présentation du bien et les visites, en recherchant une adéquation entre la propriété et le projet des acquéreurs. Le périmètre de diffusion et les supports sont précisés au cadrage. Stephan réalise également des prestations de home staging pour mettre en valeur les espaces et faciliter la projection des acquéreurs.'],
    ['Suivre la négociation', 'Vous disposez d’un interlocuteur pour les retours, les échanges et le suivi de votre projet jusqu’aux étapes convenues avec les professionnels concernés.'],
  ] : [
    ['Understand your property', 'We discuss its features, condition, available documents, your objectives and timing. The property’s specific characteristics come before a pricing recommendation.'],
    ['Agree a sales strategy', 'Valuation and relevant comparisons inform the discussion about price, presentation and marketing. The scope and terms of the engagement are agreed with you.'],
    ['Present and qualify', 'We coordinate property presentation and viewings, looking for a fit between the property and buyers’ plans. Marketing channels and materials are defined during scoping. Stephan also provides home staging services to showcase the space and help buyers picture themselves living there.'],
    ['Support the negotiation', 'You have a point of contact for feedback, discussions and follow-up through the agreed stages with the professionals involved.'],
  ];
  const buyerSteps = fr ? [
    ['Cadrer votre recherche', 'Usage du bien, secteurs souhaités, budget envisagé, calendrier, critères indispensables : nous distinguons vos priorités des compromis possibles.'],
    ['Sélectionner les biens', 'La recherche s’appuie sur vos critères et les opportunités réellement disponibles. Vous pouvez aussi nous contacter à propos d’un bien publié sur le site.'],
    ['Organiser les visites', 'Nous préparons les questions utiles et comparons les biens dans leur contexte : environnement, accès, configuration et points à vérifier avec les professionnels compétents.'],
    ['Accompagner votre projet', 'Nous facilitons les échanges et la coordination. Les questions juridiques, fiscales ou de financement sont traitées par les professionnels habilités, pas remplacées par un conseil immobilier.'],
  ] : [
    ['Define your search', 'Intended use, preferred areas, indicative budget, timing and essential features: together we distinguish priorities from possible compromises.'],
    ['Shortlist available properties', 'The search is based on your criteria and properties actually available. You can also contact us about a property listed on this website.'],
    ['Organize viewings', 'We prepare useful questions and compare properties in context: surroundings, access, layout and matters to check with the relevant professionals.'],
    ['Support your purchase', 'We facilitate discussions and coordination. Qualified professionals handle legal, tax and financing matters; property advice does not replace their work.'],
  ];
  const localLinks = fr ? [['Valbonne', '/fr/agence-immobiliere-valbonne'], ['Biot', '/fr/agence-immobiliere-biot'], ['Mougins', '/fr/immobilier-prestige-mougins']] : [['French Riviera expertise', '/en/french-riviera-real-estate'], ['Luxury villas on the French Riviera', '/en/luxury-villa-for-sale-french-riviera']];
  return <main className="container py-16">
    <header className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-widest text-zinc-600">{fr ? 'Stephan · Accompagnement en français et en anglais' : 'Stephan · Guidance in French and English'}</p><h1 className="font-luxe text-4xl mt-4">{fr ? 'Vendre ou acheter sur la Côte d’Azur, avec un interlocuteur local.' : 'Sell or buy on the French Riviera with a local point of contact.'}</h1><p className="mt-5 text-lg leading-8 text-zinc-700">{fr ? 'Votre projet ne se résume pas à une annonce. Côte d’Azur Agency vous accompagne à Valbonne, Biot, Mougins et sur les secteurs de la Côte d’Azur correspondant à votre recherche ou à votre bien.' : 'Your project is more than a listing. Côte d’Azur Agency supports you in Valbonne, Biot, Mougins and the French Riviera locations relevant to your property or search.'}</p><div className="mt-7 flex flex-wrap gap-4"><a className="btn-gold" href="#vendre">{fr ? 'Je souhaite vendre' : 'I want to sell'}</a><a className="btn-dark" href="#acheter">{fr ? 'Je souhaite acheter' : 'I want to buy'}</a></div></header>
    <section id="vendre" className="mt-16 scroll-mt-36" aria-labelledby="seller-title"><h2 id="seller-title" className="font-luxe text-3xl">{fr ? 'Vendre : un positionnement argumenté et une commercialisation adaptée.' : 'Selling: informed positioning and a tailored marketing approach.'}</h2><p className="mt-4 max-w-3xl leading-7 text-zinc-700">{fr ? 'Le premier échange permet de comprendre la propriété et de préparer les informations nécessaires à son estimation. Nous ne promettons ni prix de vente ni délai avant d’avoir étudié le dossier.' : 'The first discussion helps us understand the property and prepare the information needed for valuation. We do not promise a selling price or completion date before reviewing the details.'}</p><div className="mt-7 grid gap-5 md:grid-cols-2">{sellerSteps.map(([title, text], index) => <article key={title} className="card-luxe p-6"><p className="text-sm text-zinc-500">0{index + 1}</p><h3 className="mt-2 font-luxe text-2xl">{title}</h3><p className="mt-3 leading-7 text-zinc-700">{text}</p>{index === 2 ? <a className="inline-block mt-4 underline underline-offset-4" href="#home-staging">{fr ? 'Découvrir notre prestation de home staging' : 'Explore our home staging service'} →</a> : null}</article>)}</div><HomeStagingSection fr={fr}/><div className="mt-6 flex flex-wrap gap-4"><Link className="btn-gold" href={`/${lang}/contact?projet=estimation`} data-conversion="valuation_contact">{fr ? 'Faire estimer mon bien' : 'Discuss my property’s value'}</Link><Link className="underline underline-offset-4 self-center" href={fr ? '/fr/estimation-immobiliere-cote-azur' : '/en/french-riviera-real-estate'}>{fr ? 'Comprendre l’estimation immobilière' : 'Explore our French Riviera expertise'}</Link></div></section>
    <section id="acheter" className="mt-16 scroll-mt-36" aria-labelledby="buyer-title"><h2 id="buyer-title" className="font-luxe text-3xl">{fr ? 'Acheter : une recherche guidée par votre projet de vie.' : 'Buying: a search shaped around your plans.'}</h2><p className="mt-4 max-w-3xl leading-7 text-zinc-700">{fr ? 'Résidence principale, pied-à-terre ou changement de région : nous commençons par vos critères. La sélection et les modalités d’accompagnement sont définies ensemble.' : 'A main residence, a second home or a relocation: we start with your priorities. The search scope and the terms of our support are agreed together.'}</p><div className="mt-7 grid gap-5 md:grid-cols-2">{buyerSteps.map(([title, text], index) => <article key={title} className="card-luxe p-6"><p className="text-sm text-zinc-500">0{index + 1}</p><h3 className="mt-2 font-luxe text-2xl">{title}</h3><p className="mt-3 leading-7 text-zinc-700">{text}</p></article>)}</div><div className="mt-6 flex flex-wrap gap-4"><Link className="btn-gold" href={`/${lang}/contact?projet=achat`} data-conversion="buyer_contact">{fr ? 'Confier ma recherche' : 'Discuss my property search'}</Link><Link className="btn-dark" href={`/${lang}/vente`}>{fr ? 'Voir les biens à la vente' : 'View available properties'}</Link></div></section>
    <section className="mt-16 card-luxe p-8"><h2 className="font-luxe text-3xl">{fr ? 'Vous achetez depuis l’étranger ?' : 'Buying from abroad?'}</h2><p className="mt-4 leading-7 text-zinc-700">{fr ? 'Les échanges peuvent se dérouler en français ou en anglais. Nous préparons avec vous la recherche, l’organisation des visites et les points de coordination à anticiper. Notre réseau de partenaires peut compléter l’accompagnement selon votre situation et les prestations convenues.' : 'We can work with you in French or English to prepare your search, organize viewings and identify coordination needs. Our partner network may complement the service depending on your circumstances and the agreed scope.'}</p><p className="mt-3 leading-7 text-zinc-700">{fr ? 'Le partenariat avec Currencies Direct concerne notamment les besoins de change et de transferts. Les conditions et les conseils de ce partenaire restent distincts de notre mission immobilière.' : 'Our partnership with Currencies Direct can help address currency exchange and transfer needs. Its terms and advice remain separate from our property engagement.'}</p><Link className="inline-block mt-5 underline underline-offset-4" href={`/${lang}/agence/partenaires`}>{fr ? 'Découvrir les partenaires' : 'Meet our partners'} →</Link></section>
    <section className="mt-14"><h2 className="font-luxe text-3xl">{fr ? 'Choisir un secteur, pas seulement un bien.' : 'Choose an area, not just a property.'}</h2><p className="mt-4 text-zinc-700">{fr ? 'Explorez nos pages locales, puis précisez les quartiers et les critères importants pour vous.' : 'Explore our area guides, then tell us which locations and features matter to you.'}</p><nav className="mt-5 flex flex-wrap gap-5" aria-label={fr ? 'Expertise locale' : 'Local expertise'}>{localLinks.map(([label, href]) => <Link key={href} className="underline" href={href}>{label}</Link>)}</nav></section>
    <section className="mt-14 border-t pt-10"><h2 className="font-luxe text-3xl">{fr ? 'Préparons le premier échange.' : 'Prepare our first conversation.'}</h2><p className="mt-4 max-w-3xl text-zinc-700 leading-7">{fr ? 'Pour vendre : indiquez la commune, le type de bien et votre calendrier. Pour acheter : précisez les secteurs, le budget envisagé et les critères essentiels. N’envoyez pas de documents sensibles dans le formulaire de premier contact.' : 'To sell: tell us the location, property type and timing. To buy: share preferred areas, an indicative budget and essential features. Please do not send sensitive documents through the initial contact form.'}</p><Link className="btn-gold inline-flex mt-6" href={`/${lang}/contact`}>{fr ? 'Échanger avec Stephan' : 'Speak with Stephan'}</Link></section>
  </main>;
}
